name: Static and unit tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "wheel/**"
      - "runci/**"
  release:
    types:
      - created
      - edited
  schedule:
    # 04:00 every Tuesday morning
    - cron: "0 4 * * 2"

env:
  PYTKET_REMOTE_QUANTINUUM_USERNAME: ${{ secrets.PYTKET_REMOTE_QUANTINUUM_USERNAME }}
  PYTKET_REMOTE_QUANTINUUM_PASSWORD: ${{ secrets.PYTKET_REMOTE_QUANTINUUM_PASSWORD }}
  PYTKET_REMOTE_QUANTINUUM_USERNAME_QA: ${{ secrets.PYTKET_REMOTE_QUANTINUUM_USERNAME_QA }}
  PYTKET_REMOTE_QUANTINUUM_PASSWORD_QA: ${{ secrets.PYTKET_REMOTE_QUANTINUUM_PASSWORD_QA }}

jobs:
  static-checks:
    name: Static tests
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        pyver: ["3.12"]
    uses: CQCL/pytket-workflows/.github/workflows/static-checks-wf.yml@v0.0.9
    with:
      os: ${{ matrix.os }}
      pyver: ${{ matrix.pyver }}

  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        pyver: ["3.10", "3.13"]
    uses: CQCL/pytket-workflows/.github/workflows/unit-test-wf.yml@v0.0.9
    with:
      os: ${{ matrix.os }}
      pyver: ${{ matrix.pyver }}

  remote-tests:
    name: Remote Unit tests
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        pyver: ["3.11"]
    uses: CQCL/pytket-workflows/.github/workflows/unit-test-remote-wf.yml@v0.0.9
    with:
      os: ${{ matrix.os }}
      pyver: ${{ matrix.pyver }}
    secrets:
      PYTKET_REMOTE_QUANTINUUM_USERNAME: ${{ secrets.PYTKET_REMOTE_QUANTINUUM_USERNAME }}
      PYTKET_REMOTE_QUANTINUUM_PASSWORD: ${{ secrets.PYTKET_REMOTE_QUANTINUUM_PASSWORD }}
      PYTKET_REMOTE_QUANTINUUM_USERNAME_QA: ${{ secrets.PYTKET_REMOTE_QUANTINUUM_USERNAME_QA }}
      PYTKET_REMOTE_QUANTINUUM_PASSWORD_QA: ${{ secrets.PYTKET_REMOTE_QUANTINUUM_PASSWORD_QA }}
